// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARtPccbbqgMhHAmyTg4UBwfKusvNEs7cQ',
    appId: '1:385133722078:web:af5372fbcc47b70f27454f',
    messagingSenderId: '385133722078',
    projectId: 'ting-5b91d',
    authDomain: 'ting-5b91d.firebaseapp.com',
    storageBucket: 'ting-5b91d.firebasestorage.app',
    measurementId: 'G-D5KRE8NPCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJMm7eHjXCoDgseUcGMxmsVqR-Hgm7so0',
    appId: '1:385133722078:android:108ba0a3fe6e706e27454f',
    messagingSenderId: '385133722078',
    projectId: 'ting-5b91d',
    storageBucket: 'ting-5b91d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWckVlfCmnZwTj4KDovLIxM7Wz8r8XXjU',
    appId: '1:385133722078:ios:8093182e13abb82427454f',
    messagingSenderId: '385133722078',
    projectId: 'ting-5b91d',
    storageBucket: 'ting-5b91d.firebasestorage.app',
    iosBundleId: 'com.example.ting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWckVlfCmnZwTj4KDovLIxM7Wz8r8XXjU',
    appId: '1:385133722078:ios:8093182e13abb82427454f',
    messagingSenderId: '385133722078',
    projectId: 'ting-5b91d',
    storageBucket: 'ting-5b91d.firebasestorage.app',
    iosBundleId: 'com.example.ting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARtPccbbqgMhHAmyTg4UBwfKusvNEs7cQ',
    appId: '1:385133722078:web:60d1d8ea5b59d9aa27454f',
    messagingSenderId: '385133722078',
    projectId: 'ting-5b91d',
    authDomain: 'ting-5b91d.firebaseapp.com',
    storageBucket: 'ting-5b91d.firebasestorage.app',
    measurementId: 'G-5SYNP4C08T',
  );

}